apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: hlf
spec:
  version: "{{ .TagName }}"
  homepage: https://github.com/hyperledger/bevel-operator-fabric
  shortDescription: "Deploy and manage Hyperledger Fabric components"
  description: |
    The kubectl-hlf plugin wraps the HLF Operator and provides a simple
    interface to create and manage Hyperledger Fabric Peers, 
    Orderers and Certificate authorities
  caveats: |
    * For resources that are not in default namespace, currently you must
      specify -n/--namespace explicitly (the current namespace setting is not
      yet used).
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/hyperledger/bevel-operator-fabric/releases/download/{{ .TagName }}/hlf-operator_{{ .TagName }}_darwin_amd64.zip" .TagName | indent 6 }}
      bin: kubectl-hlf
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      {{addURIAndSha "https://github.com/hyperledger/bevel-operator-fabric/releases/download/{{ .TagName }}/hlf-operator_{{ .TagName }}_darwin_arm64.zip" .TagName | indent 6 }}
      bin: kubectl-hlf
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/hyperledger/bevel-operator-fabric/releases/download/{{ .TagName }}/hlf-operator_{{ .TagName }}_linux_amd64.zip" .TagName | indent 6 }}
      bin: kubectl-hlf
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      {{addURIAndSha "https://github.com/hyperledger/bevel-operator-fabric/releases/download/{{ .TagName }}/hlf-operator_{{ .TagName }}_linux_arm64.zip" .TagName | indent 6 }}
      bin: kubectl-hlf
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      {{addURIAndSha "https://github.com/hyperledger/bevel-operator-fabric/releases/download/{{ .TagName }}/hlf-operator_{{ .TagName }}_windows_amd64.zip" .TagName | indent 6 }}
      bin: kubectl-hlf.exe
