/*
 * Copyright Kungfusoftware.es. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AddressOverrideApplyConfiguration represents a declarative configuration of the AddressOverride type for use
// with apply.
type AddressOverrideApplyConfiguration struct {
	From        *string `json:"from,omitempty"`
	To          *string `json:"to,omitempty"`
	CACertsFile *string `json:"caCertsFile,omitempty"`
}

// AddressOverrideApplyConfiguration constructs a declarative configuration of the AddressOverride type for use with
// apply.
func AddressOverride() *AddressOverrideApplyConfiguration {
	return &AddressOverrideApplyConfiguration{}
}

// WithFrom sets the From field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the From field is set to the value of the last call.
func (b *AddressOverrideApplyConfiguration) WithFrom(value string) *AddressOverrideApplyConfiguration {
	b.From = &value
	return b
}

// WithTo sets the To field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the To field is set to the value of the last call.
func (b *AddressOverrideApplyConfiguration) WithTo(value string) *AddressOverrideApplyConfiguration {
	b.To = &value
	return b
}

// WithCACertsFile sets the CACertsFile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CACertsFile field is set to the value of the last call.
func (b *AddressOverrideApplyConfiguration) WithCACertsFile(value string) *AddressOverrideApplyConfiguration {
	b.CACertsFile = &value
	return b
}
