/*
 * Copyright Kungfusoftware.es. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// FabricNetworkConfigExternalOrdererApplyConfiguration represents a declarative configuration of the FabricNetworkConfigExternalOrderer type for use
// with apply.
type FabricNetworkConfigExternalOrdererApplyConfiguration struct {
	Name      *string `json:"name,omitempty"`
	URL       *string `json:"url,omitempty"`
	TLSCACert *string `json:"tlsCACert,omitempty"`
	MSPID     *string `json:"mspID,omitempty"`
}

// FabricNetworkConfigExternalOrdererApplyConfiguration constructs a declarative configuration of the FabricNetworkConfigExternalOrderer type for use with
// apply.
func FabricNetworkConfigExternalOrderer() *FabricNetworkConfigExternalOrdererApplyConfiguration {
	return &FabricNetworkConfigExternalOrdererApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *FabricNetworkConfigExternalOrdererApplyConfiguration) WithName(value string) *FabricNetworkConfigExternalOrdererApplyConfiguration {
	b.Name = &value
	return b
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *FabricNetworkConfigExternalOrdererApplyConfiguration) WithURL(value string) *FabricNetworkConfigExternalOrdererApplyConfiguration {
	b.URL = &value
	return b
}

// WithTLSCACert sets the TLSCACert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSCACert field is set to the value of the last call.
func (b *FabricNetworkConfigExternalOrdererApplyConfiguration) WithTLSCACert(value string) *FabricNetworkConfigExternalOrdererApplyConfiguration {
	b.TLSCACert = &value
	return b
}

// WithMSPID sets the MSPID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MSPID field is set to the value of the last call.
func (b *FabricNetworkConfigExternalOrdererApplyConfiguration) WithMSPID(value string) *FabricNetworkConfigExternalOrdererApplyConfiguration {
	b.MSPID = &value
	return b
}
