// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// FabricCABCCSPApplyConfiguration represents an declarative configuration of the FabricCABCCSP type for use
// with apply.
type FabricCABCCSPApplyConfiguration struct {
	Default *string                            `json:"default,omitempty"`
	SW      *FabricCABCCSPSWApplyConfiguration `json:"sw,omitempty"`
}

// FabricCABCCSPApplyConfiguration constructs an declarative configuration of the FabricCABCCSP type for use with
// apply.
func FabricCABCCSP() *FabricCABCCSPApplyConfiguration {
	return &FabricCABCCSPApplyConfiguration{}
}

// WithDefault sets the Default field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Default field is set to the value of the last call.
func (b *FabricCABCCSPApplyConfiguration) WithDefault(value string) *FabricCABCCSPApplyConfiguration {
	b.Default = &value
	return b
}

// WithSW sets the SW field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SW field is set to the value of the last call.
func (b *FabricCABCCSPApplyConfiguration) WithSW(value *FabricCABCCSPSWApplyConfiguration) *FabricCABCCSPApplyConfiguration {
	b.SW = value
	return b
}
