/*
 * Copyright Kungfusoftware.es. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// FabricPeerExternalRefApplyConfiguration represents a declarative configuration of the FabricPeerExternalRef type for use
// with apply.
type FabricPeerExternalRefApplyConfiguration struct {
	URL       *string `json:"url,omitempty"`
	TLSCACert *string `json:"tlsCACert,omitempty"`
}

// FabricPeerExternalRefApplyConfiguration constructs a declarative configuration of the FabricPeerExternalRef type for use with
// apply.
func FabricPeerExternalRef() *FabricPeerExternalRefApplyConfiguration {
	return &FabricPeerExternalRefApplyConfiguration{}
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *FabricPeerExternalRefApplyConfiguration) WithURL(value string) *FabricPeerExternalRefApplyConfiguration {
	b.URL = &value
	return b
}

// WithTLSCACert sets the TLSCACert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSCACert field is set to the value of the last call.
func (b *FabricPeerExternalRefApplyConfiguration) WithTLSCACert(value string) *FabricPeerExternalRefApplyConfiguration {
	b.TLSCACert = &value
	return b
}
