/*
 * Copyright Kungfusoftware.es. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// InstalledPeerApplyConfiguration represents a declarative configuration of the InstalledPeer type for use
// with apply.
type InstalledPeerApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
}

// InstalledPeerApplyConfiguration constructs a declarative configuration of the InstalledPeer type for use with
// apply.
func InstalledPeer() *InstalledPeerApplyConfiguration {
	return &InstalledPeerApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *InstalledPeerApplyConfiguration) WithName(value string) *InstalledPeerApplyConfiguration {
	b.Name = &value
	return b
}
