/*
 * Copyright Kungfusoftware.es. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kfsoftware/hlf-operator/pkg/apis/hlf.kungfusoftware.es/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// FabricChaincodeTemplateLister helps list FabricChaincodeTemplates.
// All objects returned here must be treated as read-only.
type FabricChaincodeTemplateLister interface {
	// List lists all FabricChaincodeTemplates in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.FabricChaincodeTemplate, err error)
	// FabricChaincodeTemplates returns an object that can list and get FabricChaincodeTemplates.
	FabricChaincodeTemplates(namespace string) FabricChaincodeTemplateNamespaceLister
	FabricChaincodeTemplateListerExpansion
}

// fabricChaincodeTemplateLister implements the FabricChaincodeTemplateLister interface.
type fabricChaincodeTemplateLister struct {
	listers.ResourceIndexer[*v1alpha1.FabricChaincodeTemplate]
}

// NewFabricChaincodeTemplateLister returns a new FabricChaincodeTemplateLister.
func NewFabricChaincodeTemplateLister(indexer cache.Indexer) FabricChaincodeTemplateLister {
	return &fabricChaincodeTemplateLister{listers.New[*v1alpha1.FabricChaincodeTemplate](indexer, v1alpha1.Resource("fabricchaincodetemplate"))}
}

// FabricChaincodeTemplates returns an object that can list and get FabricChaincodeTemplates.
func (s *fabricChaincodeTemplateLister) FabricChaincodeTemplates(namespace string) FabricChaincodeTemplateNamespaceLister {
	return fabricChaincodeTemplateNamespaceLister{listers.NewNamespaced[*v1alpha1.FabricChaincodeTemplate](s.ResourceIndexer, namespace)}
}

// FabricChaincodeTemplateNamespaceLister helps list and get FabricChaincodeTemplates.
// All objects returned here must be treated as read-only.
type FabricChaincodeTemplateNamespaceLister interface {
	// List lists all FabricChaincodeTemplates in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.FabricChaincodeTemplate, err error)
	// Get retrieves the FabricChaincodeTemplate from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.FabricChaincodeTemplate, error)
	FabricChaincodeTemplateNamespaceListerExpansion
}

// fabricChaincodeTemplateNamespaceLister implements the FabricChaincodeTemplateNamespaceLister
// interface.
type fabricChaincodeTemplateNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.FabricChaincodeTemplate]
}
