/*
 * Copyright Kungfusoftware.es. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kfsoftware/hlf-operator/pkg/apis/hlf.kungfusoftware.es/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// FabricChaincodeLister helps list FabricChaincodes.
// All objects returned here must be treated as read-only.
type FabricChaincodeLister interface {
	// List lists all FabricChaincodes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.FabricChaincode, err error)
	// FabricChaincodes returns an object that can list and get FabricChaincodes.
	FabricChaincodes(namespace string) FabricChaincodeNamespaceLister
	FabricChaincodeListerExpansion
}

// fabricChaincodeLister implements the FabricChaincodeLister interface.
type fabricChaincodeLister struct {
	listers.ResourceIndexer[*v1alpha1.FabricChaincode]
}

// NewFabricChaincodeLister returns a new FabricChaincodeLister.
func NewFabricChaincodeLister(indexer cache.Indexer) FabricChaincodeLister {
	return &fabricChaincodeLister{listers.New[*v1alpha1.FabricChaincode](indexer, v1alpha1.Resource("fabricchaincode"))}
}

// FabricChaincodes returns an object that can list and get FabricChaincodes.
func (s *fabricChaincodeLister) FabricChaincodes(namespace string) FabricChaincodeNamespaceLister {
	return fabricChaincodeNamespaceLister{listers.NewNamespaced[*v1alpha1.FabricChaincode](s.ResourceIndexer, namespace)}
}

// FabricChaincodeNamespaceLister helps list and get FabricChaincodes.
// All objects returned here must be treated as read-only.
type FabricChaincodeNamespaceLister interface {
	// List lists all FabricChaincodes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.FabricChaincode, err error)
	// Get retrieves the FabricChaincode from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.FabricChaincode, error)
	FabricChaincodeNamespaceListerExpansion
}

// fabricChaincodeNamespaceLister implements the FabricChaincodeNamespaceLister
// interface.
type fabricChaincodeNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.FabricChaincode]
}
