/*
 * Copyright Kungfusoftware.es. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kfsoftware/hlf-operator/pkg/apis/hlf.kungfusoftware.es/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// FabricOperatorUILister helps list FabricOperatorUIs.
// All objects returned here must be treated as read-only.
type FabricOperatorUILister interface {
	// List lists all FabricOperatorUIs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.FabricOperatorUI, err error)
	// FabricOperatorUIs returns an object that can list and get FabricOperatorUIs.
	FabricOperatorUIs(namespace string) FabricOperatorUINamespaceLister
	FabricOperatorUIListerExpansion
}

// fabricOperatorUILister implements the FabricOperatorUILister interface.
type fabricOperatorUILister struct {
	listers.ResourceIndexer[*v1alpha1.FabricOperatorUI]
}

// NewFabricOperatorUILister returns a new FabricOperatorUILister.
func NewFabricOperatorUILister(indexer cache.Indexer) FabricOperatorUILister {
	return &fabricOperatorUILister{listers.New[*v1alpha1.FabricOperatorUI](indexer, v1alpha1.Resource("fabricoperatorui"))}
}

// FabricOperatorUIs returns an object that can list and get FabricOperatorUIs.
func (s *fabricOperatorUILister) FabricOperatorUIs(namespace string) FabricOperatorUINamespaceLister {
	return fabricOperatorUINamespaceLister{listers.NewNamespaced[*v1alpha1.FabricOperatorUI](s.ResourceIndexer, namespace)}
}

// FabricOperatorUINamespaceLister helps list and get FabricOperatorUIs.
// All objects returned here must be treated as read-only.
type FabricOperatorUINamespaceLister interface {
	// List lists all FabricOperatorUIs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.FabricOperatorUI, err error)
	// Get retrieves the FabricOperatorUI from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.FabricOperatorUI, error)
	FabricOperatorUINamespaceListerExpansion
}

// fabricOperatorUINamespaceLister implements the FabricOperatorUINamespaceLister
// interface.
type fabricOperatorUINamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.FabricOperatorUI]
}
