/*
 * Copyright Kungfusoftware.es. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kfsoftware/hlf-operator/pkg/apis/hlf.kungfusoftware.es/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// FabricPeerLister helps list FabricPeers.
// All objects returned here must be treated as read-only.
type FabricPeerLister interface {
	// List lists all FabricPeers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.FabricPeer, err error)
	// FabricPeers returns an object that can list and get FabricPeers.
	FabricPeers(namespace string) FabricPeerNamespaceLister
	FabricPeerListerExpansion
}

// fabricPeerLister implements the FabricPeerLister interface.
type fabricPeerLister struct {
	listers.ResourceIndexer[*v1alpha1.FabricPeer]
}

// NewFabricPeerLister returns a new FabricPeerLister.
func NewFabricPeerLister(indexer cache.Indexer) FabricPeerLister {
	return &fabricPeerLister{listers.New[*v1alpha1.FabricPeer](indexer, v1alpha1.Resource("fabricpeer"))}
}

// FabricPeers returns an object that can list and get FabricPeers.
func (s *fabricPeerLister) FabricPeers(namespace string) FabricPeerNamespaceLister {
	return fabricPeerNamespaceLister{listers.NewNamespaced[*v1alpha1.FabricPeer](s.ResourceIndexer, namespace)}
}

// FabricPeerNamespaceLister helps list and get FabricPeers.
// All objects returned here must be treated as read-only.
type FabricPeerNamespaceLister interface {
	// List lists all FabricPeers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.FabricPeer, err error)
	// Get retrieves the FabricPeer from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.FabricPeer, error)
	FabricPeerNamespaceListerExpansion
}

// fabricPeerNamespaceLister implements the FabricPeerNamespaceLister
// interface.
type fabricPeerNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.FabricPeer]
}
