
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - pods/log
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - pods/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  resources:
  - pods/log
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  resources:
  - pods/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  resources:
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - console
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - console/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - console/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabriccas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabriccas/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabriccas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricchaincodeapproves
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricchaincodeapproves/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricchaincodeapproves/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricchaincodecommits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricchaincodecommits/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricchaincodecommits/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricchaincodeinstalls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricchaincodeinstalls/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricchaincodeinstalls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricchaincodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricchaincodes/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricchaincodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricchaincodetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricchaincodetemplates/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricchaincodetemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricfollowerchannels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricfollowerchannels/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricfollowerchannels/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricidentities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricidentities/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricidentities/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricmainchannels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricmainchannels/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricmainchannels/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricnetworkconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricnetworkconfigs/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricnetworkconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricoperationsconsoles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricoperationsconsoles/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricoperationsconsoles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricoperatorapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricoperatorapis/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricoperatorapis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricoperatoruis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricoperatoruis/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricoperatoruis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricorderernodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricorderernodes/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricorderernodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricorderingservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricorderingservices/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricorderingservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricpeers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricpeers/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hlf.kungfusoftware.es
  resources:
  - fabricpeers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - podmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - gateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
