apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hlf-peer.fullname" . }}--peer
  labels:
{{ include "labels.standard" . | indent 4 }}
data:
  CORE_PEER_ID: {{ .Release.Name }}
  CORE_PEER_NETWORKID: {{ .Release.Name }}-nid
  CORE_PEER_ADDRESSAUTODETECT: "true"
  # If we have an ingress, we set hostname to it
  CORE_PEER_ADDRESS: {{ .Values.externalHost }}
  CORE_PEER_GOSSIP_EXTERNALENDPOINT: {{ .Values.peer.gossip.externalEndpoint | quote }}
  CORE_PEER_GOSSIP_BOOTSTRAP: {{ .Values.peer.gossip.bootstrap | quote }}
  CORE_PEER_GOSSIP_ENDPOINT: {{ .Values.peer.gossip.endpoint | quote }}
  CORE_PEER_LISTENADDRESS: 0.0.0.0:7051
  CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
  CORE_PEER_EVENTS_ADDRESS: 0.0.0.0:7053
  CORE_PEER_COMMITTER_ENABLED: "true"
  CORE_PEER_PROFILE_ENABLED: "true"
  CORE_PEER_DISCOVERY_PERIOD: 60s
  CORE_PEER_DISCOVERY_TOUCHPERIOD: 60s
  CORE_PEER_LOCALMSPID: {{ .Values.peer.mspID | quote }}
  CORE_PEER_MSPCONFIGPATH: /var/hyperledger/msp
  ##############
  # Operations #
  ##############
  CORE_OPERATIONS_TLS_ENABLED: "false"
  CORE_OPERATIONS_TLS_KEY_FILE: "/var/hyperledger/tls/operations/pair/tls.key"
  CORE_OPERATIONS_TLS_CERT_FILE: "/var/hyperledger/tls/operations/pair/tls.crt"
  CORE_OPERATIONS_TLS_CLIENTAUTHREQUIRED: "false"
  CORE_OPERATIONS_LISTENADDRESS: "0.0.0.0:9443"
  CORE_OPERATIONS_TLS_CLIENTROOTCAS_FILES: "/var/hyperledger/tls/server/cert/cacert.pem"
  ##############
  # Events #
  ##############
  CORE_PEER_EVENTS_ADDRESS: "0.0.0.0:7053"
  ##############
  # Metrics #
  ##############
  CORE_METRICS_PROVIDER: "prometheus"
  # Logging #
  ###########
  #CORE_LOGGING_LEVEL: {{ .Values.logging.level | quote }}
  FABRIC_LOGGING_SPEC: {{ .Values.logging.level | quote }}
  CORE_LOGGING_PEER: {{ .Values.logging.peer | quote }}
  CORE_LOGGING_CAUTHDSL: {{ .Values.logging.cauthdsl | quote }}
  CORE_LOGGING_GOSSIP: {{ .Values.logging.gossip | quote }}
  CORE_LOGGING_LEDGER: {{ .Values.logging.ledger | quote }}
  CORE_LOGGING_MSP: {{ .Values.logging.msp | quote }}
  CORE_LOGGING_POLICIES: {{ .Values.logging.policies | quote }}
  CORE_LOGGING_GRPC: {{ .Values.logging.grpc | quote }}
  ##########
  # Gossip #
  ##########

  CORE_PEER_GOSSIP_ORGLEADER: {{ .Values.peer.gossip.orgLeader | quote }}
  CORE_PEER_GOSSIP_USELEADERELECTION: {{ .Values.peer.gossip.useLeaderElection | quote }}
  ##########
  # TLS    #
  ##########
  CORE_PEER_TLS_ENABLED: {{ .Values.peer.tls.server.enabled | quote }}
  CORE_PEER_TLS_CERT_FILE: "/var/hyperledger/tls/server/pair/tls.crt"
  CORE_PEER_TLS_KEY_FILE: "/var/hyperledger/tls/server/pair/tls.key"
  CORE_PEER_TLS_ROOTCERT_FILE: "/var/hyperledger/tls/server/cert/cacert.pem"
  CORE_PEER_TLS_CLIENTAUTHREQUIRED: {{ .Values.peer.tls.client.enabled | quote }}
  # This is fixed prior to starting the peer
  CORE_PEER_TLS_CLIENTROOTCAS_FILES: "/var/hyperledger/tls/client/cert/*"
  CORE_PEER_TLS_CLIENTCERT_FILE: "/var/hyperledger/tls/client/pair/tls.crt"
  CORE_PEER_TLS_CLIENTKEY_FILE: "/var/hyperledger/tls/client/pair/tls.key"
  {{- if .Values.dockerSocketPath }}
  CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
  {{- end }}
  CORE_LEDGER_STATE_STATEDATABASE: {{ .Values.peer.databaseType | quote }}
  {{- if .Values.externalChaincodeBuilder }}
  CORE_CHAINCODEADDRESS: "{{ include "hlf-peer.fullname" . }}:7052"
  {{- end }}
  # Containers in the same pod share the host
  {{- if eq .Values.peer.databaseType "CouchDB" }}
  {{- if .Values.couchdb.external.enabled }}
  CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS: {{.Values.couchdb.external.host}}:{{.Values.couchdb.external.port}}
  {{- else }}
  CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS: localhost:5984
  {{- end }}
  {{- end }}
  PEER_CFG_PATH: /var/hyperledger/config
  FABRIC_CFG_PATH: /var/hyperledger/fabric_cfg
  ADMIN_MSP_PATH: /var/hyperledger/admin_msp
  ORD_TLS_PATH: /var/hyperledger/tls/ord/cert