{
 "title": "Hyperledger Fabric Monitoring",
 "description": "Hyperledger Fabric Monitoring Dashboard.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time left",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "hlf_operator_certificate_expiration_timestamp_seconds{} - time()",
     "legendFormat": "{{exported_namespace}} / {{name}}"
    }
   ]
  },
  {
   "title": "Hyperledger Fabric Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fabric Version",
     "type": "stat",
     "description": "The active version of Fabric.",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "first" ] } },
     "targets": [
      { "expr": "fabric_version" }
     ]
    },
    {
     "title": "Go Version",
     "type": "stat",
     "description": "The active version of Go.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "first" ] } },
     "targets": [
      { "expr": "go_info" }
     ]
    },
    {
     "title": "Ledger Block Height",
     "type": "stat",
     "description": "Height of the chain in blocks. ",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      { "expr": "ledger_blockchain_height" }
     ]
    },
    {
     "title": "Ledger Transaction Count",
     "type": "stat",
     "description": "Number of transactions processed.",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      { "expr": "ledger_transaction_count" }
     ]
    },
    {
     "title": "Endorsment Proposal Requests",
     "type": "stat",
     "description": "The number of proposals received.",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      { "expr": "endorser_proposals_received" }
     ]
    },
    {
     "title": "Endorsment Proposal Successful",
     "type": "stat",
     "description": "The number of successful proposals. ",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      { "expr": "endorser_successful_proposals" }
     ]
    },
    {
     "title": "Couch DB Processing Time",
     "type": "graph",
     "description": "Time taken in seconds for the function to complete request to CouchDB.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(couchdb_processing_time_bucket[5m])) by (le))",
       "legendFormat": "CouchDB"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go Memory Allocations",
     "type": "graph",
     "description": "go_memstats_alloc_bytes",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "go_memstats_alloc_bytes", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "Go Heap Objects",
     "type": "graph",
     "description": "go_memstats_alloc_bytes",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_heap_objects{job!=\"prometheus\"}[5m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Go Garbage Collection",
     "type": "graph",
     "description": "go_gc_duration_seconds",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds[5m])",
       "legendFormat": "{{instance}}/{{job}}"
      }
     ]
    },
    {
     "title": "Go Free Memory",
     "type": "graph",
     "description": "go_gc_duration_seconds",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_frees_total[5m])",
       "legendFormat": "{{instance}}/{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ledger Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ledger Block Processing Time",
     "type": "graph",
     "description": "Time taken in seconds for ledger block processing.",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(ledger_block_processing_time_bucket[5m])) by (le))",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "StateDB Commit Time",
     "type": "graph",
     "description": "Time taken in seconds for committing block changes to state db.",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(ledger_statedb_commit_time_bucket[5m])) by (le))",
       "legendFormat": " "
      }
     ]
    }
   ]
  },
  { "title": "Orderer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Orderer Broadcasts",
   "type": "table-old",
   "description": "The number of transactions processed.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    { "expr": "broadcast_processed_count" }
   ]
  },
  { "title": "Chaincode Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Chaincode Shim Requests",
   "type": "graph",
   "description": "chaincode_shim_requests_received",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(chaincode_shim_requests_received[5m])",
     "legendFormat": "{{channel}}, {{Received}}, {{chaincode}}, {{type}}"
    },
    {
     "expr": "rate(chaincode_shim_requests_completed[5m])",
     "legendFormat": "{{channel}}, {{Completed}},  {{chaincode}}, {{type}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(chaincode_shim_request_duration_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Broadcast Enqueu",
   "type": "graph",
   "description": "broadcast_enqueue_duration_sum",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_frees_total{job!=\"prometheus\"}[5m])",
     "legendFormat": "{{channel}}, {{job}}"
    }
   ]
  },
  {
   "title": "gRPC Closed Connections",
   "type": "graph",
   "description": "rate(grpc_comm_conn_closed[5m])",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_comm_conn_closed[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Chaincode Launch Duration",
   "type": "graph",
   "description": "chaincode_shim_requests_received",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "chaincode_launch_duration_count",
     "legendFormat": "{{Count}}, {{chaincode}}"
    },
    { "expr": "chaincode_launch_duration_sum", "legendFormat": "{{Tota}}, {{chaincode}}" }
   ]
  }
 ]
}