/*
 * Copyright Kungfusoftware.es. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package applyconfiguration

import (
	v1alpha1 "github.com/kfsoftware/hlf-operator/api/hlf.kungfusoftware.es/v1alpha1"
	hlfkungfusoftwareesv1alpha1 "github.com/kfsoftware/hlf-operator/pkg/client/applyconfiguration/hlf.kungfusoftware.es/v1alpha1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=hlf.kungfusoftware.es, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("ApplicationCapabilities"):
		return &hlfkungfusoftwareesv1alpha1.ApplicationCapabilitiesApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Catls"):
		return &hlfkungfusoftwareesv1alpha1.CatlsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ChannelCapabilities"):
		return &hlfkungfusoftwareesv1alpha1.ChannelCapabilitiesApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ChannelConfig"):
		return &hlfkungfusoftwareesv1alpha1.ChannelConfigApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Component"):
		return &hlfkungfusoftwareesv1alpha1.ComponentApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Cors"):
		return &hlfkungfusoftwareesv1alpha1.CorsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Csr"):
		return &hlfkungfusoftwareesv1alpha1.CsrApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Enrollment"):
		return &hlfkungfusoftwareesv1alpha1.EnrollmentApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ExternalBuilder"):
		return &hlfkungfusoftwareesv1alpha1.ExternalBuilderApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ExternalCertificate"):
		return &hlfkungfusoftwareesv1alpha1.ExternalCertificateApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCA"):
		return &hlfkungfusoftwareesv1alpha1.FabricCAApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCAAffiliation"):
		return &hlfkungfusoftwareesv1alpha1.FabricCAAffiliationApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCABCCSP"):
		return &hlfkungfusoftwareesv1alpha1.FabricCABCCSPApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCABCCSPSW"):
		return &hlfkungfusoftwareesv1alpha1.FabricCABCCSPSWApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCACFG"):
		return &hlfkungfusoftwareesv1alpha1.FabricCACFGApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCACFGAffilitions"):
		return &hlfkungfusoftwareesv1alpha1.FabricCACFGAffilitionsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCACFGIdentities"):
		return &hlfkungfusoftwareesv1alpha1.FabricCACFGIdentitiesApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCAClientAuth"):
		return &hlfkungfusoftwareesv1alpha1.FabricCAClientAuthApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCACRL"):
		return &hlfkungfusoftwareesv1alpha1.FabricCACRLApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCACrypto"):
		return &hlfkungfusoftwareesv1alpha1.FabricCACryptoApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCACSR"):
		return &hlfkungfusoftwareesv1alpha1.FabricCACSRApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCACSRCA"):
		return &hlfkungfusoftwareesv1alpha1.FabricCACSRCAApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCADatabase"):
		return &hlfkungfusoftwareesv1alpha1.FabricCADatabaseApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCAIdentity"):
		return &hlfkungfusoftwareesv1alpha1.FabricCAIdentityApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCAIdentityAttrs"):
		return &hlfkungfusoftwareesv1alpha1.FabricCAIdentityAttrsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCAIntermediate"):
		return &hlfkungfusoftwareesv1alpha1.FabricCAIntermediateApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCAIntermediateParentServer"):
		return &hlfkungfusoftwareesv1alpha1.FabricCAIntermediateParentServerApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCAItemConf"):
		return &hlfkungfusoftwareesv1alpha1.FabricCAItemConfApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCAMetrics"):
		return &hlfkungfusoftwareesv1alpha1.FabricCAMetricsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCAMetricsStatsd"):
		return &hlfkungfusoftwareesv1alpha1.FabricCAMetricsStatsdApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCANames"):
		return &hlfkungfusoftwareesv1alpha1.FabricCANamesApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCARegistry"):
		return &hlfkungfusoftwareesv1alpha1.FabricCARegistryApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCASigning"):
		return &hlfkungfusoftwareesv1alpha1.FabricCASigningApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCASigningDefault"):
		return &hlfkungfusoftwareesv1alpha1.FabricCASigningDefaultApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCASigningProfiles"):
		return &hlfkungfusoftwareesv1alpha1.FabricCASigningProfilesApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCASigningSignProfile"):
		return &hlfkungfusoftwareesv1alpha1.FabricCASigningSignProfileApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCASigningSignProfileConstraint"):
		return &hlfkungfusoftwareesv1alpha1.FabricCASigningSignProfileConstraintApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCASigningTLSProfile"):
		return &hlfkungfusoftwareesv1alpha1.FabricCASigningTLSProfileApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCASpec"):
		return &hlfkungfusoftwareesv1alpha1.FabricCASpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCASpecService"):
		return &hlfkungfusoftwareesv1alpha1.FabricCASpecServiceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCAStatus"):
		return &hlfkungfusoftwareesv1alpha1.FabricCAStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCASubject"):
		return &hlfkungfusoftwareesv1alpha1.FabricCASubjectApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricCATLSConf"):
		return &hlfkungfusoftwareesv1alpha1.FabricCATLSConfApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricChaincode"):
		return &hlfkungfusoftwareesv1alpha1.FabricChaincodeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricChaincodeSpec"):
		return &hlfkungfusoftwareesv1alpha1.FabricChaincodeSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricChaincodeStatus"):
		return &hlfkungfusoftwareesv1alpha1.FabricChaincodeStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricExplorer"):
		return &hlfkungfusoftwareesv1alpha1.FabricExplorerApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricExplorerSpec"):
		return &hlfkungfusoftwareesv1alpha1.FabricExplorerSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricExplorerStatus"):
		return &hlfkungfusoftwareesv1alpha1.FabricExplorerStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricFollowerChannel"):
		return &hlfkungfusoftwareesv1alpha1.FabricFollowerChannelApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricFollowerChannelAnchorPeer"):
		return &hlfkungfusoftwareesv1alpha1.FabricFollowerChannelAnchorPeerApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricFollowerChannelExternalPeer"):
		return &hlfkungfusoftwareesv1alpha1.FabricFollowerChannelExternalPeerApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricFollowerChannelOrderer"):
		return &hlfkungfusoftwareesv1alpha1.FabricFollowerChannelOrdererApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricFollowerChannelPeer"):
		return &hlfkungfusoftwareesv1alpha1.FabricFollowerChannelPeerApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricFollowerChannelSpec"):
		return &hlfkungfusoftwareesv1alpha1.FabricFollowerChannelSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricFollowerChannelStatus"):
		return &hlfkungfusoftwareesv1alpha1.FabricFollowerChannelStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricFSServer"):
		return &hlfkungfusoftwareesv1alpha1.FabricFSServerApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricIdentity"):
		return &hlfkungfusoftwareesv1alpha1.FabricIdentityApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricIdentityRegister"):
		return &hlfkungfusoftwareesv1alpha1.FabricIdentityRegisterApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricIdentitySpec"):
		return &hlfkungfusoftwareesv1alpha1.FabricIdentitySpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricIdentityStatus"):
		return &hlfkungfusoftwareesv1alpha1.FabricIdentityStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricIstio"):
		return &hlfkungfusoftwareesv1alpha1.FabricIstioApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricMainChannel"):
		return &hlfkungfusoftwareesv1alpha1.FabricMainChannelApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricMainChannelAdminOrdererOrganizationSpec"):
		return &hlfkungfusoftwareesv1alpha1.FabricMainChannelAdminOrdererOrganizationSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricMainChannelAdminPeerOrganizationSpec"):
		return &hlfkungfusoftwareesv1alpha1.FabricMainChannelAdminPeerOrganizationSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricMainChannelApplicationConfig"):
		return &hlfkungfusoftwareesv1alpha1.FabricMainChannelApplicationConfigApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricMainChannelConfig"):
		return &hlfkungfusoftwareesv1alpha1.FabricMainChannelConfigApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricMainChannelConsenter"):
		return &hlfkungfusoftwareesv1alpha1.FabricMainChannelConsenterApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricMainChannelEtcdRaft"):
		return &hlfkungfusoftwareesv1alpha1.FabricMainChannelEtcdRaftApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricMainChannelEtcdRaftOptions"):
		return &hlfkungfusoftwareesv1alpha1.FabricMainChannelEtcdRaftOptionsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricMainChannelExternalOrdererNode"):
		return &hlfkungfusoftwareesv1alpha1.FabricMainChannelExternalOrdererNodeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricMainChannelExternalOrdererOrganization"):
		return &hlfkungfusoftwareesv1alpha1.FabricMainChannelExternalOrdererOrganizationApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricMainChannelExternalPeerOrganization"):
		return &hlfkungfusoftwareesv1alpha1.FabricMainChannelExternalPeerOrganizationApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricMainChannelIdentity"):
		return &hlfkungfusoftwareesv1alpha1.FabricMainChannelIdentityApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricMainChannelOrdererBatchSize"):
		return &hlfkungfusoftwareesv1alpha1.FabricMainChannelOrdererBatchSizeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricMainChannelOrdererConfig"):
		return &hlfkungfusoftwareesv1alpha1.FabricMainChannelOrdererConfigApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricMainChannelOrdererNode"):
		return &hlfkungfusoftwareesv1alpha1.FabricMainChannelOrdererNodeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricMainChannelOrdererOrganization"):
		return &hlfkungfusoftwareesv1alpha1.FabricMainChannelOrdererOrganizationApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricMainChannelPeerOrganization"):
		return &hlfkungfusoftwareesv1alpha1.FabricMainChannelPeerOrganizationApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricMainChannelPoliciesConfig"):
		return &hlfkungfusoftwareesv1alpha1.FabricMainChannelPoliciesConfigApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricMainChannelSpec"):
		return &hlfkungfusoftwareesv1alpha1.FabricMainChannelSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricMainChannelStatus"):
		return &hlfkungfusoftwareesv1alpha1.FabricMainChannelStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricNetworkConfig"):
		return &hlfkungfusoftwareesv1alpha1.FabricNetworkConfigApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricNetworkConfigIdentity"):
		return &hlfkungfusoftwareesv1alpha1.FabricNetworkConfigIdentityApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricNetworkConfigSpec"):
		return &hlfkungfusoftwareesv1alpha1.FabricNetworkConfigSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricNetworkConfigStatus"):
		return &hlfkungfusoftwareesv1alpha1.FabricNetworkConfigStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOperationsConsole"):
		return &hlfkungfusoftwareesv1alpha1.FabricOperationsConsoleApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOperationsConsoleAuth"):
		return &hlfkungfusoftwareesv1alpha1.FabricOperationsConsoleAuthApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOperationsConsoleCouchDB"):
		return &hlfkungfusoftwareesv1alpha1.FabricOperationsConsoleCouchDBApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOperationsConsoleSpec"):
		return &hlfkungfusoftwareesv1alpha1.FabricOperationsConsoleSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOperationsConsoleStatus"):
		return &hlfkungfusoftwareesv1alpha1.FabricOperationsConsoleStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOperatorAPI"):
		return &hlfkungfusoftwareesv1alpha1.FabricOperatorAPIApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOperatorAPIAuth"):
		return &hlfkungfusoftwareesv1alpha1.FabricOperatorAPIAuthApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOperatorAPIHLFConfig"):
		return &hlfkungfusoftwareesv1alpha1.FabricOperatorAPIHLFConfigApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOperatorAPINetworkConfig"):
		return &hlfkungfusoftwareesv1alpha1.FabricOperatorAPINetworkConfigApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOperatorAPISpec"):
		return &hlfkungfusoftwareesv1alpha1.FabricOperatorAPISpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOperatorAPIStatus"):
		return &hlfkungfusoftwareesv1alpha1.FabricOperatorAPIStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOperatorUI"):
		return &hlfkungfusoftwareesv1alpha1.FabricOperatorUIApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOperatorUIAuth"):
		return &hlfkungfusoftwareesv1alpha1.FabricOperatorUIAuthApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOperatorUISpec"):
		return &hlfkungfusoftwareesv1alpha1.FabricOperatorUISpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOperatorUIStatus"):
		return &hlfkungfusoftwareesv1alpha1.FabricOperatorUIStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOrdererNode"):
		return &hlfkungfusoftwareesv1alpha1.FabricOrdererNodeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOrdererNodeSpec"):
		return &hlfkungfusoftwareesv1alpha1.FabricOrdererNodeSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOrdererNodeStatus"):
		return &hlfkungfusoftwareesv1alpha1.FabricOrdererNodeStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOrderingService"):
		return &hlfkungfusoftwareesv1alpha1.FabricOrderingServiceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOrderingServiceSpec"):
		return &hlfkungfusoftwareesv1alpha1.FabricOrderingServiceSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricOrderingServiceStatus"):
		return &hlfkungfusoftwareesv1alpha1.FabricOrderingServiceStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricPeer"):
		return &hlfkungfusoftwareesv1alpha1.FabricPeerApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricPeerCouchDB"):
		return &hlfkungfusoftwareesv1alpha1.FabricPeerCouchDBApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricPeerCouchdbExporter"):
		return &hlfkungfusoftwareesv1alpha1.FabricPeerCouchdbExporterApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricPeerDiscovery"):
		return &hlfkungfusoftwareesv1alpha1.FabricPeerDiscoveryApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricPeerExternalCouchDB"):
		return &hlfkungfusoftwareesv1alpha1.FabricPeerExternalCouchDBApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricPeerLogging"):
		return &hlfkungfusoftwareesv1alpha1.FabricPeerLoggingApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricPeerResources"):
		return &hlfkungfusoftwareesv1alpha1.FabricPeerResourcesApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricPeerSpec"):
		return &hlfkungfusoftwareesv1alpha1.FabricPeerSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricPeerSpecGossip"):
		return &hlfkungfusoftwareesv1alpha1.FabricPeerSpecGossipApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricPeerStatus"):
		return &hlfkungfusoftwareesv1alpha1.FabricPeerStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricPeerStorage"):
		return &hlfkungfusoftwareesv1alpha1.FabricPeerStorageApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FabricTLSCACrypto"):
		return &hlfkungfusoftwareesv1alpha1.FabricTLSCACryptoApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GRPCProxy"):
		return &hlfkungfusoftwareesv1alpha1.GRPCProxyApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HLFIdentity"):
		return &hlfkungfusoftwareesv1alpha1.HLFIdentityApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Ingress"):
		return &hlfkungfusoftwareesv1alpha1.IngressApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("IngressHost"):
		return &hlfkungfusoftwareesv1alpha1.IngressHostApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("IngressPath"):
		return &hlfkungfusoftwareesv1alpha1.IngressPathApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("OrdererCapabilities"):
		return &hlfkungfusoftwareesv1alpha1.OrdererCapabilitiesApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("OrdererEnrollment"):
		return &hlfkungfusoftwareesv1alpha1.OrdererEnrollmentApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("OrdererNode"):
		return &hlfkungfusoftwareesv1alpha1.OrdererNodeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("OrdererNodeEnrollment"):
		return &hlfkungfusoftwareesv1alpha1.OrdererNodeEnrollmentApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("OrdererNodeEnrollmentTLS"):
		return &hlfkungfusoftwareesv1alpha1.OrdererNodeEnrollmentTLSApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("OrdererNodeService"):
		return &hlfkungfusoftwareesv1alpha1.OrdererNodeServiceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("OrdererService"):
		return &hlfkungfusoftwareesv1alpha1.OrdererServiceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("OrdererSystemChannel"):
		return &hlfkungfusoftwareesv1alpha1.OrdererSystemChannelApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PeerService"):
		return &hlfkungfusoftwareesv1alpha1.PeerServiceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Secret"):
		return &hlfkungfusoftwareesv1alpha1.SecretApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ServiceMonitor"):
		return &hlfkungfusoftwareesv1alpha1.ServiceMonitorApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Storage"):
		return &hlfkungfusoftwareesv1alpha1.StorageApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("TLS"):
		return &hlfkungfusoftwareesv1alpha1.TLSApplyConfiguration{}

	}
	return nil
}
