# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
  - bases/hlf.kungfusoftware.es_fabricpeers.yaml
  - bases/hlf.kungfusoftware.es_fabricorderingservices.yaml
  - bases/hlf.kungfusoftware.es_fabricorderernodes.yaml
  - bases/hlf.kungfusoftware.es_fabriccas.yaml
  - bases/hlf.kungfusoftware.es_fabricidentities.yaml
  - bases/hlf.kungfusoftware.es_fabricnetworkconfigs.yaml
  - bases/hlf.kungfusoftware.es_fabricchaincodes.yaml
  - bases/hlf.kungfusoftware.es_fabricchaincodeinstalls.yaml
  - bases/hlf.kungfusoftware.es_fabricchaincodeapproves.yaml
  - bases/hlf.kungfusoftware.es_fabricchaincodecommits.yaml
  - bases/hlf.kungfusoftware.es_fabricoperationsconsoles.yaml
  - bases/hlf.kungfusoftware.es_fabricoperatoruis.yaml
  - bases/hlf.kungfusoftware.es_fabricoperatorapis.yaml
  - bases/hlf.kungfusoftware.es_fabricmainchannels.yaml
  - bases/hlf.kungfusoftware.es_fabricfollowerchannels.yaml
  - bases/hlf.kungfusoftware.es_fabricchaincodetemplates.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_hlfs.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_hlfs.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
  - kustomizeconfig.yaml
