// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kfsoftware/hlf-operator/api/hlf.kungfusoftware.es/v1alpha1"
	scheme "github.com/kfsoftware/hlf-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FabricIdentitiesGetter has a method to return a FabricIdentityInterface.
// A group's client should implement this interface.
type FabricIdentitiesGetter interface {
	FabricIdentities(namespace string) FabricIdentityInterface
}

// FabricIdentityInterface has methods to work with FabricIdentity resources.
type FabricIdentityInterface interface {
	Create(ctx context.Context, fabricIdentity *v1alpha1.FabricIdentity, opts v1.CreateOptions) (*v1alpha1.FabricIdentity, error)
	Update(ctx context.Context, fabricIdentity *v1alpha1.FabricIdentity, opts v1.UpdateOptions) (*v1alpha1.FabricIdentity, error)
	UpdateStatus(ctx context.Context, fabricIdentity *v1alpha1.FabricIdentity, opts v1.UpdateOptions) (*v1alpha1.FabricIdentity, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.FabricIdentity, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.FabricIdentityList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FabricIdentity, err error)
	FabricIdentityExpansion
}

// fabricIdentities implements FabricIdentityInterface
type fabricIdentities struct {
	client rest.Interface
	ns     string
}

// newFabricIdentities returns a FabricIdentities
func newFabricIdentities(c *HlfV1alpha1Client, namespace string) *fabricIdentities {
	return &fabricIdentities{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the fabricIdentity, and returns the corresponding fabricIdentity object, and an error if there is any.
func (c *fabricIdentities) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FabricIdentity, err error) {
	result = &v1alpha1.FabricIdentity{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fabricidentities").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FabricIdentities that match those selectors.
func (c *fabricIdentities) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FabricIdentityList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.FabricIdentityList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("fabricidentities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested fabricIdentities.
func (c *fabricIdentities) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("fabricidentities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a fabricIdentity and creates it.  Returns the server's representation of the fabricIdentity, and an error, if there is any.
func (c *fabricIdentities) Create(ctx context.Context, fabricIdentity *v1alpha1.FabricIdentity, opts v1.CreateOptions) (result *v1alpha1.FabricIdentity, err error) {
	result = &v1alpha1.FabricIdentity{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("fabricidentities").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(fabricIdentity).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a fabricIdentity and updates it. Returns the server's representation of the fabricIdentity, and an error, if there is any.
func (c *fabricIdentities) Update(ctx context.Context, fabricIdentity *v1alpha1.FabricIdentity, opts v1.UpdateOptions) (result *v1alpha1.FabricIdentity, err error) {
	result = &v1alpha1.FabricIdentity{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("fabricidentities").
		Name(fabricIdentity.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(fabricIdentity).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *fabricIdentities) UpdateStatus(ctx context.Context, fabricIdentity *v1alpha1.FabricIdentity, opts v1.UpdateOptions) (result *v1alpha1.FabricIdentity, err error) {
	result = &v1alpha1.FabricIdentity{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("fabricidentities").
		Name(fabricIdentity.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(fabricIdentity).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the fabricIdentity and deletes it. Returns an error if one occurs.
func (c *fabricIdentities) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fabricidentities").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *fabricIdentities) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("fabricidentities").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched fabricIdentity.
func (c *fabricIdentities) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FabricIdentity, err error) {
	result = &v1alpha1.FabricIdentity{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("fabricidentities").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
