/*
 * Copyright Kungfusoftware.es. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/kfsoftware/hlf-operator/pkg/apis/hlf.kungfusoftware.es/v1alpha1"
	hlfkungfusoftwareesv1alpha1 "github.com/kfsoftware/hlf-operator/pkg/client/applyconfiguration/hlf.kungfusoftware.es/v1alpha1"
	scheme "github.com/kfsoftware/hlf-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// FabricChaincodeTemplatesGetter has a method to return a FabricChaincodeTemplateInterface.
// A group's client should implement this interface.
type FabricChaincodeTemplatesGetter interface {
	FabricChaincodeTemplates(namespace string) FabricChaincodeTemplateInterface
}

// FabricChaincodeTemplateInterface has methods to work with FabricChaincodeTemplate resources.
type FabricChaincodeTemplateInterface interface {
	Create(ctx context.Context, fabricChaincodeTemplate *v1alpha1.FabricChaincodeTemplate, opts v1.CreateOptions) (*v1alpha1.FabricChaincodeTemplate, error)
	Update(ctx context.Context, fabricChaincodeTemplate *v1alpha1.FabricChaincodeTemplate, opts v1.UpdateOptions) (*v1alpha1.FabricChaincodeTemplate, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, fabricChaincodeTemplate *v1alpha1.FabricChaincodeTemplate, opts v1.UpdateOptions) (*v1alpha1.FabricChaincodeTemplate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.FabricChaincodeTemplate, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.FabricChaincodeTemplateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FabricChaincodeTemplate, err error)
	Apply(ctx context.Context, fabricChaincodeTemplate *hlfkungfusoftwareesv1alpha1.FabricChaincodeTemplateApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.FabricChaincodeTemplate, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, fabricChaincodeTemplate *hlfkungfusoftwareesv1alpha1.FabricChaincodeTemplateApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.FabricChaincodeTemplate, err error)
	FabricChaincodeTemplateExpansion
}

// fabricChaincodeTemplates implements FabricChaincodeTemplateInterface
type fabricChaincodeTemplates struct {
	*gentype.ClientWithListAndApply[*v1alpha1.FabricChaincodeTemplate, *v1alpha1.FabricChaincodeTemplateList, *hlfkungfusoftwareesv1alpha1.FabricChaincodeTemplateApplyConfiguration]
}

// newFabricChaincodeTemplates returns a FabricChaincodeTemplates
func newFabricChaincodeTemplates(c *HlfV1alpha1Client, namespace string) *fabricChaincodeTemplates {
	return &fabricChaincodeTemplates{
		gentype.NewClientWithListAndApply[*v1alpha1.FabricChaincodeTemplate, *v1alpha1.FabricChaincodeTemplateList, *hlfkungfusoftwareesv1alpha1.FabricChaincodeTemplateApplyConfiguration](
			"fabricchaincodetemplates",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.FabricChaincodeTemplate { return &v1alpha1.FabricChaincodeTemplate{} },
			func() *v1alpha1.FabricChaincodeTemplateList { return &v1alpha1.FabricChaincodeTemplateList{} }),
	}
}
