/*
 * Copyright Kungfusoftware.es. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/kfsoftware/hlf-operator/pkg/apis/hlf.kungfusoftware.es/v1alpha1"
	hlfkungfusoftwareesv1alpha1 "github.com/kfsoftware/hlf-operator/pkg/client/applyconfiguration/hlf.kungfusoftware.es/v1alpha1"
	scheme "github.com/kfsoftware/hlf-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// FabricOrdererNodesGetter has a method to return a FabricOrdererNodeInterface.
// A group's client should implement this interface.
type FabricOrdererNodesGetter interface {
	FabricOrdererNodes(namespace string) FabricOrdererNodeInterface
}

// FabricOrdererNodeInterface has methods to work with FabricOrdererNode resources.
type FabricOrdererNodeInterface interface {
	Create(ctx context.Context, fabricOrdererNode *v1alpha1.FabricOrdererNode, opts v1.CreateOptions) (*v1alpha1.FabricOrdererNode, error)
	Update(ctx context.Context, fabricOrdererNode *v1alpha1.FabricOrdererNode, opts v1.UpdateOptions) (*v1alpha1.FabricOrdererNode, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, fabricOrdererNode *v1alpha1.FabricOrdererNode, opts v1.UpdateOptions) (*v1alpha1.FabricOrdererNode, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.FabricOrdererNode, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.FabricOrdererNodeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FabricOrdererNode, err error)
	Apply(ctx context.Context, fabricOrdererNode *hlfkungfusoftwareesv1alpha1.FabricOrdererNodeApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.FabricOrdererNode, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, fabricOrdererNode *hlfkungfusoftwareesv1alpha1.FabricOrdererNodeApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.FabricOrdererNode, err error)
	FabricOrdererNodeExpansion
}

// fabricOrdererNodes implements FabricOrdererNodeInterface
type fabricOrdererNodes struct {
	*gentype.ClientWithListAndApply[*v1alpha1.FabricOrdererNode, *v1alpha1.FabricOrdererNodeList, *hlfkungfusoftwareesv1alpha1.FabricOrdererNodeApplyConfiguration]
}

// newFabricOrdererNodes returns a FabricOrdererNodes
func newFabricOrdererNodes(c *HlfV1alpha1Client, namespace string) *fabricOrdererNodes {
	return &fabricOrdererNodes{
		gentype.NewClientWithListAndApply[*v1alpha1.FabricOrdererNode, *v1alpha1.FabricOrdererNodeList, *hlfkungfusoftwareesv1alpha1.FabricOrdererNodeApplyConfiguration](
			"fabricorderernodes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.FabricOrdererNode { return &v1alpha1.FabricOrdererNode{} },
			func() *v1alpha1.FabricOrdererNodeList { return &v1alpha1.FabricOrdererNodeList{} }),
	}
}
