/*
 * Copyright Kungfusoftware.es. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/kfsoftware/hlf-operator/pkg/apis/hlf.kungfusoftware.es/v1alpha1"
	hlfkungfusoftwareesv1alpha1 "github.com/kfsoftware/hlf-operator/pkg/client/applyconfiguration/hlf.kungfusoftware.es/v1alpha1"
	scheme "github.com/kfsoftware/hlf-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// FabricFollowerChannelsGetter has a method to return a FabricFollowerChannelInterface.
// A group's client should implement this interface.
type FabricFollowerChannelsGetter interface {
	FabricFollowerChannels() FabricFollowerChannelInterface
}

// FabricFollowerChannelInterface has methods to work with FabricFollowerChannel resources.
type FabricFollowerChannelInterface interface {
	Create(ctx context.Context, fabricFollowerChannel *v1alpha1.FabricFollowerChannel, opts v1.CreateOptions) (*v1alpha1.FabricFollowerChannel, error)
	Update(ctx context.Context, fabricFollowerChannel *v1alpha1.FabricFollowerChannel, opts v1.UpdateOptions) (*v1alpha1.FabricFollowerChannel, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, fabricFollowerChannel *v1alpha1.FabricFollowerChannel, opts v1.UpdateOptions) (*v1alpha1.FabricFollowerChannel, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.FabricFollowerChannel, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.FabricFollowerChannelList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FabricFollowerChannel, err error)
	Apply(ctx context.Context, fabricFollowerChannel *hlfkungfusoftwareesv1alpha1.FabricFollowerChannelApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.FabricFollowerChannel, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, fabricFollowerChannel *hlfkungfusoftwareesv1alpha1.FabricFollowerChannelApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.FabricFollowerChannel, err error)
	FabricFollowerChannelExpansion
}

// fabricFollowerChannels implements FabricFollowerChannelInterface
type fabricFollowerChannels struct {
	*gentype.ClientWithListAndApply[*v1alpha1.FabricFollowerChannel, *v1alpha1.FabricFollowerChannelList, *hlfkungfusoftwareesv1alpha1.FabricFollowerChannelApplyConfiguration]
}

// newFabricFollowerChannels returns a FabricFollowerChannels
func newFabricFollowerChannels(c *HlfV1alpha1Client) *fabricFollowerChannels {
	return &fabricFollowerChannels{
		gentype.NewClientWithListAndApply[*v1alpha1.FabricFollowerChannel, *v1alpha1.FabricFollowerChannelList, *hlfkungfusoftwareesv1alpha1.FabricFollowerChannelApplyConfiguration](
			"fabricfollowerchannels",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.FabricFollowerChannel { return &v1alpha1.FabricFollowerChannel{} },
			func() *v1alpha1.FabricFollowerChannelList { return &v1alpha1.FabricFollowerChannelList{} }),
	}
}
