/*
 * Copyright Kungfusoftware.es. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/kfsoftware/hlf-operator/pkg/apis/hlf.kungfusoftware.es/v1alpha1"
	hlfkungfusoftwareesv1alpha1 "github.com/kfsoftware/hlf-operator/pkg/client/applyconfiguration/hlf.kungfusoftware.es/v1alpha1"
	scheme "github.com/kfsoftware/hlf-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// FabricOperationsConsolesGetter has a method to return a FabricOperationsConsoleInterface.
// A group's client should implement this interface.
type FabricOperationsConsolesGetter interface {
	FabricOperationsConsoles(namespace string) FabricOperationsConsoleInterface
}

// FabricOperationsConsoleInterface has methods to work with FabricOperationsConsole resources.
type FabricOperationsConsoleInterface interface {
	Create(ctx context.Context, fabricOperationsConsole *v1alpha1.FabricOperationsConsole, opts v1.CreateOptions) (*v1alpha1.FabricOperationsConsole, error)
	Update(ctx context.Context, fabricOperationsConsole *v1alpha1.FabricOperationsConsole, opts v1.UpdateOptions) (*v1alpha1.FabricOperationsConsole, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, fabricOperationsConsole *v1alpha1.FabricOperationsConsole, opts v1.UpdateOptions) (*v1alpha1.FabricOperationsConsole, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.FabricOperationsConsole, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.FabricOperationsConsoleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FabricOperationsConsole, err error)
	Apply(ctx context.Context, fabricOperationsConsole *hlfkungfusoftwareesv1alpha1.FabricOperationsConsoleApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.FabricOperationsConsole, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, fabricOperationsConsole *hlfkungfusoftwareesv1alpha1.FabricOperationsConsoleApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.FabricOperationsConsole, err error)
	FabricOperationsConsoleExpansion
}

// fabricOperationsConsoles implements FabricOperationsConsoleInterface
type fabricOperationsConsoles struct {
	*gentype.ClientWithListAndApply[*v1alpha1.FabricOperationsConsole, *v1alpha1.FabricOperationsConsoleList, *hlfkungfusoftwareesv1alpha1.FabricOperationsConsoleApplyConfiguration]
}

// newFabricOperationsConsoles returns a FabricOperationsConsoles
func newFabricOperationsConsoles(c *HlfV1alpha1Client, namespace string) *fabricOperationsConsoles {
	return &fabricOperationsConsoles{
		gentype.NewClientWithListAndApply[*v1alpha1.FabricOperationsConsole, *v1alpha1.FabricOperationsConsoleList, *hlfkungfusoftwareesv1alpha1.FabricOperationsConsoleApplyConfiguration](
			"fabricoperationsconsoles",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.FabricOperationsConsole { return &v1alpha1.FabricOperationsConsole{} },
			func() *v1alpha1.FabricOperationsConsoleList { return &v1alpha1.FabricOperationsConsoleList{} }),
	}
}
