/*
 * Copyright Kungfusoftware.es. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/kfsoftware/hlf-operator/pkg/apis/hlf.kungfusoftware.es/v1alpha1"
	hlfkungfusoftwareesv1alpha1 "github.com/kfsoftware/hlf-operator/pkg/client/applyconfiguration/hlf.kungfusoftware.es/v1alpha1"
	scheme "github.com/kfsoftware/hlf-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// FabricExplorersGetter has a method to return a FabricExplorerInterface.
// A group's client should implement this interface.
type FabricExplorersGetter interface {
	FabricExplorers(namespace string) FabricExplorerInterface
}

// FabricExplorerInterface has methods to work with FabricExplorer resources.
type FabricExplorerInterface interface {
	Create(ctx context.Context, fabricExplorer *v1alpha1.FabricExplorer, opts v1.CreateOptions) (*v1alpha1.FabricExplorer, error)
	Update(ctx context.Context, fabricExplorer *v1alpha1.FabricExplorer, opts v1.UpdateOptions) (*v1alpha1.FabricExplorer, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, fabricExplorer *v1alpha1.FabricExplorer, opts v1.UpdateOptions) (*v1alpha1.FabricExplorer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.FabricExplorer, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.FabricExplorerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FabricExplorer, err error)
	Apply(ctx context.Context, fabricExplorer *hlfkungfusoftwareesv1alpha1.FabricExplorerApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.FabricExplorer, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, fabricExplorer *hlfkungfusoftwareesv1alpha1.FabricExplorerApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.FabricExplorer, err error)
	FabricExplorerExpansion
}

// fabricExplorers implements FabricExplorerInterface
type fabricExplorers struct {
	*gentype.ClientWithListAndApply[*v1alpha1.FabricExplorer, *v1alpha1.FabricExplorerList, *hlfkungfusoftwareesv1alpha1.FabricExplorerApplyConfiguration]
}

// newFabricExplorers returns a FabricExplorers
func newFabricExplorers(c *HlfV1alpha1Client, namespace string) *fabricExplorers {
	return &fabricExplorers{
		gentype.NewClientWithListAndApply[*v1alpha1.FabricExplorer, *v1alpha1.FabricExplorerList, *hlfkungfusoftwareesv1alpha1.FabricExplorerApplyConfiguration](
			"fabricexplorers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.FabricExplorer { return &v1alpha1.FabricExplorer{} },
			func() *v1alpha1.FabricExplorerList { return &v1alpha1.FabricExplorerList{} }),
	}
}
