/*
 * Copyright Kungfusoftware.es. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/kfsoftware/hlf-operator/pkg/apis/hlf.kungfusoftware.es/v1alpha1"
	hlfkungfusoftwareesv1alpha1 "github.com/kfsoftware/hlf-operator/pkg/client/applyconfiguration/hlf.kungfusoftware.es/v1alpha1"
	scheme "github.com/kfsoftware/hlf-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// FabricChaincodeApprovesGetter has a method to return a FabricChaincodeApproveInterface.
// A group's client should implement this interface.
type FabricChaincodeApprovesGetter interface {
	FabricChaincodeApproves() FabricChaincodeApproveInterface
}

// FabricChaincodeApproveInterface has methods to work with FabricChaincodeApprove resources.
type FabricChaincodeApproveInterface interface {
	Create(ctx context.Context, fabricChaincodeApprove *v1alpha1.FabricChaincodeApprove, opts v1.CreateOptions) (*v1alpha1.FabricChaincodeApprove, error)
	Update(ctx context.Context, fabricChaincodeApprove *v1alpha1.FabricChaincodeApprove, opts v1.UpdateOptions) (*v1alpha1.FabricChaincodeApprove, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, fabricChaincodeApprove *v1alpha1.FabricChaincodeApprove, opts v1.UpdateOptions) (*v1alpha1.FabricChaincodeApprove, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.FabricChaincodeApprove, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.FabricChaincodeApproveList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FabricChaincodeApprove, err error)
	Apply(ctx context.Context, fabricChaincodeApprove *hlfkungfusoftwareesv1alpha1.FabricChaincodeApproveApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.FabricChaincodeApprove, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, fabricChaincodeApprove *hlfkungfusoftwareesv1alpha1.FabricChaincodeApproveApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.FabricChaincodeApprove, err error)
	FabricChaincodeApproveExpansion
}

// fabricChaincodeApproves implements FabricChaincodeApproveInterface
type fabricChaincodeApproves struct {
	*gentype.ClientWithListAndApply[*v1alpha1.FabricChaincodeApprove, *v1alpha1.FabricChaincodeApproveList, *hlfkungfusoftwareesv1alpha1.FabricChaincodeApproveApplyConfiguration]
}

// newFabricChaincodeApproves returns a FabricChaincodeApproves
func newFabricChaincodeApproves(c *HlfV1alpha1Client) *fabricChaincodeApproves {
	return &fabricChaincodeApproves{
		gentype.NewClientWithListAndApply[*v1alpha1.FabricChaincodeApprove, *v1alpha1.FabricChaincodeApproveList, *hlfkungfusoftwareesv1alpha1.FabricChaincodeApproveApplyConfiguration](
			"fabricchaincodeapproves",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *v1alpha1.FabricChaincodeApprove { return &v1alpha1.FabricChaincodeApprove{} },
			func() *v1alpha1.FabricChaincodeApproveList { return &v1alpha1.FabricChaincodeApproveList{} }),
	}
}
